### ISSUE TITLE
Elements on the publications webpage are not aligned

### ISSUE THREAD

**Issue by alexanderbock** [ImmVis/ImmVis.github.io#8]
Depending on the width of the thumbnail image, the other elements in the table row start at different widths

![image](https://github.com/ImmVis/ImmVis.github.io/assets/4921724/ba9f4ee8-2d4a-4c4a-8d39-8854e663c8d0)

**Comment by Golen87** [comment]
Fixed. This was caused by a bug in flexbox on Firefox where width is undefined.
